# Generated by Django 4.0.6 on 2022-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('brand', models.CharField(max_length=55)),
                ('qty', models.PositiveIntegerField()),
            ],
        ),
    ]
