# Generated by Django 4.0.6 on 2022-08-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_doctors', models.ManyToManyField(related_name='patient_doctors', to='users.doctorprofile')),
                ('medicines', models.ManyToManyField(blank=True, null=True, related_name='patient_medicines', to='pharmacy.medicine')),
                ('patient_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile')),
            ],
        ),
    ]
