# Generated by Django 4.0.6 on 2022-08-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medicines',
            field=models.ManyToManyField(related_name='patient_medicines', to='pharmacy.medicine'),
        ),
    ]
